### ISSUE TITLE
Signer fails on sidechain configuration

### ISSUE THREAD

**Issue by akru** [airalab/robonomics_comm#112]
**Error log**
```
[ERROR] [1559294196.867483]: bad callback: <function Signer.__init__.<locals>.sign_offer at 0x7fcbedbc1e18>
ript-liability-start[882]: Traceback (most recent call last):
ript-liability-start[882]:   File "/nix/store/z5qzs91jqskq6kgyad93q5cid6z0vvhv-rospy-1.14.4/lib/python3.7/site-packages/rospy/topics.py>
ript-liability-start[882]:     cb(msg)
ript-liability-start[882]:   File "/nix/store/psxml9bk7d4g61g3lvxy8fm7gnib5bg0-robonomics_comm-1.0.0/lib/python3.7/site-packages/ethere>
ript-liability-start[882]:     message_hash = robonomicsMessageUtils.offer_hash(msg, current_nonce)
ript-liability-start[882]:   File "/nix/store/psxml9bk7d4g61g3lvxy8fm7gnib5bg0-robonomics_comm-1.0.0/lib/python3.7/site-packages/robono>
ript-liability-start[882]:     msg.sender.address])
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     return self.method(objtype, *args, **kwargs)
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ma>
ript-liability-start[882]:     normalized_values = map_abi_data([abi_ens_resolver(w3)], abi_types, values)
ript-liability-start[882]:   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     return pipe(data, *pipeline)
ript-liability-start[882]:   File "cytoolz/functoolz.pyx", line 589, in cytoolz.functoolz.pipe
ript-liability-start[882]:   File "cytoolz/functoolz.pyx", line 565, in cytoolz.functoolz.c_pipe
ript-liability-start[882]:   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     return recursive_map(map_to_typed_data, data_tree)
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     wrapped_val = to_wrap(*args)
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     items_mapped = map_collection(recurse, data)
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     return datatype(map(func, collection))
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     return recursive_map(func, item)
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     wrapped_val = to_wrap(*args)
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     return func(items_mapped)
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     return ABITypedData(func(*elements))
ript-liability-start[882]:   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
ript-liability-start[882]:   File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/ut>
ript-liability-start[882]:     " connection available" % (val)
ript-liability-start[882]: web3.exceptions.InvalidAddress: Could not look up name 'airalab.lighthouse.5.robonomics.sid' because no web3  connection available
```

**Description**

This error raise on offer to sign publish.
* distro: AIRA unstable, eval 808
* robonomics_comm: 1.0
* network: sidechain

**Comment by akru** [comment]
The error was reached when invalid content filled into lighthouse field of Offer message.
