### ISSUE TITLE
Confusing signer node exception message on incorrect Ethereum address

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#115]
Hi.

I've attempted to publish a Demand with wrong Validator address:
```console
rostopic pub -1 /liability/infochan/eth/signing/demand robonomics_msgs/Demand '{model: {multihash: "QmW3dTa1QZxnZzpF9TDuHKN7GDKaJDVoQys4u38xmdAGHF"}, objective: {multihash: "QmUA5ZHHqFZyR1T1KxxheyrUzEEymfKb3goPZt1jLDNEWL"}, token: {address: "0x368C35597A9068280028c424122DE9129fAF8689"}, cost: {uint256: "1"}, lighthouse: {address: "0x202a09A451DE674d2d65Bf1C90968a8d8F72cf7b"}, validator: {address: "0x0x368C35597A9068280028c424122DE9129fAF8689"}, validatorFee: {uint256: "0"}, deadline: {uint256: "210000"}, sender: {address: ""}, signature: []}'
```

As you can see, validator address contains double _0x_ prefix. There is a _Signer_ node log below where you can find it raise a web3 exception:

```console
...
web3.exceptions.InvalidAddress: Could not look up name '0x0x368C35597A9068280028c424122DE9129fAF8689' because no web3 connection available
```

Exception name _InvalidAddress_ gives a tip, but message "no web3 connection" makes confuse.

<details>
  <summary>liability-infochan-eth-signer-4.log</summary>

```console
[rospy.client][INFO] 2019-06-12 13:34:28,654: init_node, name[/liability/infochan/eth/signer], pid[1078]
[xmlrpc][INFO] 2019-06-12 13:34:28,661: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-12 13:34:28,661: Started XML-RPC server [http://iotipciAira:33477/]
[rospy.impl.masterslave][INFO] 2019-06-12 13:34:28,662: _ready: http://iotipciAira:33477/
[rospy.init][INFO] 2019-06-12 13:34:28,671: ROS Slave URI: [http://iotipciAira:33477/]
[rospy.registration][INFO] 2019-06-12 13:34:28,672: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2019-06-12 13:34:28,679: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-06-12 13:34:28,771: registered with master
[rospy.rosout][INFO] 2019-06-12 13:34:28,772: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-12 13:34:28,774: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-12 13:34:28,776: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-06-12 13:34:29,005: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-12 13:34:33,617: topic[/liability/infochan/eth/sending/demand] adding connection to [/liability/infochan/ipfs_channel], count 0
[rospy.internal][INFO] 2019-06-12 13:34:33,626: topic[/liability/infochan/eth/sending/offer] adding connection to [/liability/infochan/ipfs_channel], count 0
[rospy.internal][INFO] 2019-06-12 13:34:33,631: topic[/liability/infochan/eth/sending/result] adding connection to [/liability/infochan/ipfs_channel], count 0
[rospy.internal][INFO] 2019-06-12 13:34:33,649: topic[/liability/infochan/eth/signing/result] adding connection to [http://iotipciAira:46633/], count 0
[rospy.internal][INFO] 2019-06-12 13:49:01,075: topic[/liability/infochan/eth/signing/demand] adding connection to [http://iotipciAira:37661/], count 0
[rospy.internal][INFO] 2019-06-12 13:49:01,081: topic[/liability/infochan/eth/signing/offer] adding connection to [http://iotipciAira:37661/], count 0

...

[rospy.internal][INFO] 2019-06-13 11:19:40,831: topic[/liability/infochan/eth/signing/demand] removing connection to http://iotipciAira:46481/
[rospy.internal][INFO] 2019-06-13 11:19:44,556: topic[/liability/infochan/eth/signing/demand] adding connection to [http://iotipciAira:40641/], count 0
[rosout][ERROR] 2019-06-13 11:19:44,572: bad callback: <function Signer.__init__.<locals>.sign_demand at 0x7f4f66c9fd90>
Traceback (most recent call last):
  File "/nix/store/z5qzs91jqskq6kgyad93q5cid6z0vvhv-rospy-1.14.4/lib/python3.7/site-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/nix/store/psxml9bk7d4g61g3lvxy8fm7gnib5bg0-robonomics_comm-1.0.0/lib/python3.7/site-packages/ethereum_common/signer.py", line 83, in sign_demand
    message_hash = robonomicsMessageUtils.demand_hash(msg, current_nonce)
  File "/nix/store/psxml9bk7d4g61g3lvxy8fm7gnib5bg0-robonomics_comm-1.0.0/lib/python3.7/site-packages/robonomics_msgs/robonomicsMessageUtils.py", line 32, in demand_hash
    msg.sender.address])
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/decorators.py", line 16, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/main.py", line 167, in soliditySha3
    normalized_values = map_abi_data([abi_ens_resolver(w3)], abi_types, values)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/abi.py", line 442, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 589, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 565, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/abi.py", line 474, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/formatters.py", line 115, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/formatters.py", line 102, in map_collection
    return datatype(map(func, collection))
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/formatters.py", line 114, in recurse
    return recursive_map(func, item)
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/formatters.py", line 116, in recursive_map
    return func(items_mapped)
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/abi.py", line 471, in map_to_typed_data
    return ABITypedData(func(*elements))
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/nix/store/d2b47n76nwwa4c9a1vnrd780rmcxpnxp-python3.7-web3-4.8.3/lib/python3.7/site-packages/web3/utils/normalizers.py", line 140, in abi_ens_resolver
    " connection available" % (val)
web3.exceptions.InvalidAddress: Could not look up name '0x0x368C35597A9068280028c424122DE9129fAF8689' because no web3 connection available

[rospy.internal][ERROR] 2019-06-13 11:19:47,558: Unable to initiate TCP/IP socket to iotipciAira:34629 (http://iotipciAira:40641/): Traceback (most recent call last):
  File "/nix/store/z5qzs91jqskq6kgyad93q5cid6z0vvhv-rospy-1.14.4/lib/python3.7/site-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/nix/store/z5qzs91jqskq6kgyad93q5cid6z0vvhv-rospy-1.14.4/lib/python3.7/site-packages/rospy/impl/tcpros_base.py", line 653, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/nix/store/z5qzs91jqskq6kgyad93q5cid6z0vvhv-rospy-1.14.4/lib/python3.7/site-packages/rospy/impl/tcpros_base.py", line 596, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2019-06-13 11:19:48,560: Unknown error initiating TCP/IP socket to iotipciAira:34629 (http://iotipciAira:40641/): Traceback (most recent call last):
  File "/nix/store/z5qzs91jqskq6kgyad93q5cid6z0vvhv-rospy-1.14.4/lib/python3.7/site-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-13 11:19:48,560: topic[/liability/infochan/eth/signing/demand] removing connection to http://iotipciAira:40641/
```
</details>

**Comment by akru** [comment]
Related to #113
