### ISSUE TITLE
Can't connect to ipfs

### ISSUE THREAD

**Issue by Vourhey** [airalab/robonomics_comm#130]
Building the latest stack (v1.1.0) on Ubuntu and launching throws the error
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/nix/store/wd7icdvjbdix0xikrgak0w1dfpxv0zpp-python3.7-urllib3-1.24.2/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/nix/store/wd7icdvjbdix0xikrgak0w1dfpxv0zpp-python3.7-urllib3-1.24.2/lib/python3.7/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/nix/store/wd7icdvjbdix0xikrgak0w1dfpxv0zpp-python3.7-urllib3-1.24.2/lib/python3.7/site-packages/urllib3/response.py", line 598, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/nix/store/fqbrwq2gvv97lb0albmfb2x212azzp46-python3-3.7.3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/il511ckmk41xhd2pgb11bsj04z53s7v8-python3.7-requests-2.21.0/lib/python3.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/nix/store/wd7icdvjbdix0xikrgak0w1dfpxv0zpp-python3.7-urllib3-1.24.2/lib/python3.7/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/nix/store/wd7icdvjbdix0xikrgak0w1dfpxv0zpp-python3.7-urllib3-1.24.2/lib/python3.7/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/nix/store/fqbrwq2gvv97lb0albmfb2x212azzp46-python3-3.7.3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/nix/store/wd7icdvjbdix0xikrgak0w1dfpxv0zpp-python3.7-urllib3-1.24.2/lib/python3.7/site-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5001): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/fqbrwq2gvv97lb0albmfb2x212azzp46-python3-3.7.3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/nix/store/fqbrwq2gvv97lb0albmfb2x212azzp46-python3-3.7.3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vadim/Projects/robonomics_dev/ws/src/robonomics_comm/ipfs_common/src/ipfs_common/ipfs_channel.py", line 48, in channel_thread
    for m in subscribe(self.ipfs_client, self.lighthouse):
  File "/home/vadim/Projects/robonomics_dev/ws/src/robonomics_comm/ipfs_common/src/ipfs_common/pubsub.py", line 24, in subscribe
    for msg in sub:
  File "/home/vadim/.local/lib/python3.7/site-packages/ipfshttpclient/http.py", line 95, in __next__
    data = next(self._response_iter)
  File "/nix/store/il511ckmk41xhd2pgb11bsj04z53s7v8-python3.7-requests-2.21.0/lib/python3.7/site-packages/requests/models.py", line 757, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Read timed out.
```
IPFS v0.4.22 is running `ipfs daemon --enable-pubsub-experiment`
Launching stack with the command:
```
# Launch liability
. ws/devel/setup.bash
roslaunch robonomics_liability liability.launch \
    lighthouse_contract:="airalab.lighthouse.5.robonomics.sid" \
    factory_contract:="factory.5.robonomics.sid" \
    graph_topic:="graph.5.robonomics.sid" \
    ens_contract:="0xaC4Ac4801b50b74aa3222B5Ba282FF54407B3941" \
    keyfile:="$WORKSPACE/keyfile" \
    keyfile_password_file:="$WORKSPACE/keyfile_password_file" \
    web3_http_provider:="https://sidechain.aira.life/rpc" \
    web3_ws_provider:="wss://sidechain.aira.life/ws" &

sleep 5

roslaunch ethereum_common erc20.launch \
    factory_contract:="factory.5.robonomics.sid" \
    erc20_token:="xrt.5.robonomics.sid" \
    ens_contract:="0xaC4Ac4801b50b74aa3222B5Ba282FF54407B3941" \
    keyfile:="$WORKSPACE/keyfile" \
    keyfile_password_file:="$WORKSPACE/keyfile_password_file" \
    web3_http_provider:="https://sidechain.aira.life/rpc" \
    web3_ws_provider:="wss://sidechain.aira.life/ws" &
```

**Comment by Vourhey** [comment]
After a while it continues 
```
[ERROR] [1569861804.828498]: ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5001): Read timed out. (read timeout=120)
```
Meanwhile I see those messages
```
[INFO] [1569861439.841361]: Published to /ipns/Qme9adaKScv7vh4WR3eYay2jaNdSt4pXbKWPnup2JaS7oc
[INFO] [1569861505.524781]: Published to /ipns/Qme9adaKScv7vh4WR3eYay2jaNdSt4pXbKWPnup2JaS7oc
```
