### ISSUE TITLE
Liability publish problem 

### ISSUE THREAD

**Issue by tuuzdu** [airalab/robonomics_comm#14]
Hello!
I have problem with `listener.py` in time when it receives event:
```
Exception in thread Thread-131:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/home/dji/catkin_ws/src/robonomics_comm/robonomics_liability/src/robonomics_liability/listener.py", line 81, in liability_filter_thread
    self.liability.publish(self.liability_read(entry['args']['liability']))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/home/dji/catkin_ws/devel/lib/python2.7/dist-packages/robonomics_liability/msg/_Liability.py", line 97, in serialize
    _x = _x.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by tuuzdu** [comment]
Temporary I fixed it by call method `decode("utf-8")` to [lines](https://github.com/airalab/robonomics_comm/blob/543ced8834bac2cb3dd60b8572489b44c15f1ead/robonomics_liability/src/robonomics_liability/listener.py#L63)

**Comment by akru** [comment]
It's a problem because you've use python2, but currently robonomics_comm is for python3 only.

**Comment by tuuzdu** [comment]
For robonomics_comm I use python3.5. ROS Kinetic uses python2.7.
Actually, when I have used python2.7 for robonomics_comm, I had a lot of errors.
But problem with generated message and my combination of python2.7 and python3.

**Comment by akru** [comment]
Combining Python2 and Python3 have a lot of potential troubles and problem on the top is a top of iceberg. Do you can use nix-channel from https://hydra.aira.life/project/aira/channel/latest?

**Comment by tuuzdu** [comment]
It works on Raspberri. I didn't try to install NixOS or Nix packet manager on it.
