### ISSUE TITLE
Error with "cost" field of message

### ISSUE THREAD

**Issue by AlexeiOvcharov** [airalab/robonomics_comm#82]
When message (offer or demand) with big value in `cost` field is sent to IPFS pubsub, the node `ipfs_common/ipfs_channel_node` crashed with error:

**Error message**
```
 [rospy.topics][ERROR] 2018-12-10 14:55:38,972: Traceback (most recent call last):
   File "/nix/store/r8ci0lxw8lzav9wiry60981zqq15rhwb-robonomics_comm-0.4/lib/python3.6/site-packages/robonomics_msgs/msg/_Demand.py", line 122, in serialize
     buff.write(_get_struct_I().pack(self.cost))
 struct.error: 'I' format requires 0 <= number <= 4294967295

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/nix/store/hpz7qzdxa0l29w8s24lx74xsbr6rd2y4-rospy-1.14.4/lib/python3.6/site-packages/rospy/topics.py", line 882, in publish
     self.impl.publish(data)
   File "/nix/store/hpz7qzdxa0l29w8s24lx74xsbr6rd2y4-rospy-1.14.4/lib/python3.6/site-packages/rospy/topics.py", line 1066, in publish
     serialize_message(b, self.seq, message)
   File "/nix/store/hpz7qzdxa0l29w8s24lx74xsbr6rd2y4-rospy-1.14.4/lib/python3.6/site-packages/rospy/msg.py", line 152, in serialize_message
     msg.serialize(b)
   File "/nix/store/r8ci0lxw8lzav9wiry60981zqq15rhwb-robonomics_comm-0.4/lib/python3.6/site-packages/robonomics_msgs/msg/_Demand.py", line 151, in serialize
     except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
   File "/nix/store/dj9mbf74jx0lrbmjg6ipykfrwzvcywxn-genpy-0.6.7/lib/python3.6/site-packages/genpy/message.py", line 334, in _check_types
     check_type(n, t, getattr(self, n))
   File "/nix/store/dj9mbf74jx0lrbmjg6ipykfrwzvcywxn-genpy-0.6.7/lib/python3.6/site-packages/genpy/message.py", line 215, in check_type
     raise SerializationError('field %s exceeds specified width [%s]'%(field_name, field_type))
 genpy.message.SerializationError: field cost exceeds specified width [uint32]
```

**Non valid Demand message in ipfs**
```
{"model":"QmWZsRae58t2jnVcHaUBYrWMdaM6vwvpSs264Cmg3MrwY6","objective":"QmYx3YLWaV8kzc3fWNwSPiq6LrgvdqUko3km5aeFgZgu26","token":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","cost":100000000000000,"validator":"0x0000000000000000000000000000000000000000","lighthouse":"0xD06Eda15582ce766000f0e88Ef94E34217bf8fB7","deadline":6946873,"nonce":"fc3585d11783017f822e5a6189c1f308e5e18febdbd653d74d634d12ceac9ed6","signature":"ac017f5f80c6bba84296c1e6cdb868d9b27153a14fb6a05da20b0c01c76288c749816d1c4413737619897ea99fbdac1386dc94fc0d858237976cf7a69fc1dd0b1c","validatorFee":0}
```

If i send cost value in range of int64, all will ok. Demand/Offer message will send by publisher.

**Comment by akru** [comment]
Fixed in https://github.com/airalab/robonomics_comm/tree/gen4 via using string type for costs and fees.
