### ISSUE TITLE
Sidechain support for ethereum_common

### ISSUE THREAD

**Issue by khssnv** [airalab/robonomics_comm#87]
I've tried `ethereum_common` on sidechain, it fails with an error, please find it and contract addresses below.

<details>
<summary>erc20.sh</summary>

```bash
roslaunch ethereum_common erc20.launch \
    ens_contract:="0x4e978ed8A05b516D8130Ff7dF54Fbc8b7ceB6442" \
    lighthouse_contract:="airalab.lighthouse.4.robonomics.sid" \
    factory_contract:="factory.4.robonomics.sid" \
    erc20_token:="xrt.4.robonomics.sid" \
    keyfile:="$WORKSPACE/keyfile" \
    keyfile_password_file:="$WORKSPACE/keyfile_password_file" \
    web3_http_provider:="https://sidechain.aira.life/rpc" \
    web3_ws_provider:="wss://sidechain.aira.life/ws"
```
</details>

<details>
<summary>source ./ethereum_common.sh   </summary>

```bash                                                                            
... logging to /home/khassanov/.ros/log/c590904a-08e0-11e9-972d-c485089fc0e0/roslaunch-32vd-6539.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://32vd:45189/

SUMMARY
========

PARAMETERS
 * /eth/erc20_token/ens_contract: 0x4e978ed8A05b516...
 * /eth/erc20_token/factory_contract: factory.4.robonom...
 * /eth/erc20_token/keyfile: /home/khassanov/W...
 * /eth/erc20_token/keyfile_password_file: /home/khassanov/W...
 * /eth/erc20_token/token_contract: xrt.4.robonomics.sid
 * /eth/erc20_token/web3_http_provider: https://sidechain...
 * /eth/erc20_token/web3_ws_provider: wss://sidechain.a...
 * /eth/eth_node/ens_contract: 0x4e978ed8A05b516...
 * /eth/eth_node/keyfile: /home/khassanov/W...
 * /eth/eth_node/keyfile_password_file: /home/khassanov/W...
 * /eth/eth_node/token_contract: xrt.4.robonomics.sid
 * /eth/eth_node/web3_http_provider: https://sidechain...
 * /eth/eth_node/web3_ws_provider: wss://sidechain.a...
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /eth/
    erc20_token (ethereum_common/erc20_node)
    eth_node (ethereum_common/eth_node)

auto-starting new master
process[master]: started with pid [6562]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c590904a-08e0-11e9-972d-c485089fc0e0
process[rosout-1]: started with pid [6578]
started core service [/rosout]
process[eth/erc20_token-2]: started with pid [6581]
process[eth/eth_node-3]: started with pid [6582]
INFO: cannot create a symlink to latest log directory
Traceback (most recent call last):
  File "/nix/store/8idx0h60nb4rzbncbvjdzi9lszhd0qa6-robonomics_comm-0.5.1/lib/ethereum_common/erc20_node", line 7, in <module>
    erc20_node()
  File "/nix/store/8idx0h60nb4rzbncbvjdzi9lszhd0qa6-robonomics_comm-0.5.1/lib/python3.7/site-packages/ethereum_common/nodes.py", line 11, in erc20_node
    erc20_services.ERC20Services().spin()
  File "/nix/store/8idx0h60nb4rzbncbvjdzi9lszhd0qa6-robonomics_comm-0.5.1/lib/python3.7/site-packages/ethereum_common/erc20_services.py", line 27, in __init__
    XRT_ABI)
  File "/nix/store/8idx0h60nb4rzbncbvjdzi9lszhd0qa6-robonomics_comm-0.5.1/lib/python3.7/site-packages/ethereum_common/eth_utils.py", line 23, in __init__
    self.erc20_balance_delimiter = (10 ** self.erc20.functions.decimals().call())
  File "/nix/store/p7yw7mbnnly02ckgqhd93zbirfvzbgfz-python3.7-web3-4.8.2/lib/python3.7/site-packages/web3/contract.py", line 1100, in call
    "Please ensure that this contract instance has an address."
ValueError: Please ensure that this contract instance has an address.
[eth/erc20_token-2] process has died [pid 6581, exit code 1, cmd /nix/store/8idx0h60nb4rzbncbvjdzi9lszhd0qa6-robonomics_comm-0.5.1/lib/ethereum_common/erc20_node __name:=erc20_token __log:=/home/khassanov/.ros/log/c590904a-08e0-11e9-972d-c485089fc0e0/eth-erc20_token-2.log].
log file: /home/khassanov/.ros/log/c590904a-08e0-11e9-972d-c485089fc0e0/eth-erc20_token-2*.log
[eth/erc20_token-2] restarting process
```
</details>

**Comment by akru** [comment]
Should be fixed in https://github.com/airalab/airapkgs/commit/ce56ca15ece1321ff5cf6a9ab52763fe41dd2fed
